permalink: pretty
theme: jekyll_patternbot

patternbot:
  layouts:
    default: |
      The default layout should be used for almost every page, it contains the website's primary header and footer.
    product: |
      The product layout should be used for the products page.
    home: |
      The home layout should be used for the home page.
  title: "Woodpushas"
  description: |
    An online skateboard goods store that carries high quality products.
  font_url: https://fonts.googleapis.com/css?family=Hind|Oswald"
  colors:
    accent: "--color-secondary"
    patterns:
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary: |
      Hind was selected because it is modern yet very readable. Hind is to be used for all body copy.
    typefaces.secondary: |
      Oswald was selected because of its modern and strong appearance. Oswald is to be used for anything that is not body copy.
    colors.primary: |
      The primary colours represent the wood used to build skateboards. They are to be used for banners and buttons.
    colors.secondary: |
      The secondary colours are darker, more neutral wood tones. They are to be used as background colours.

collections:
  products:
    output: true
  home-cards:
    output: true

defaults:
  - scope:
      path: _products
    values:
      layout: product
  - scope:
      path: _home-cards
    values:
      layout: home
