title: "Forms and Fields"
description: |
  Forms and fields are to be used on the checkout page so the customer can enter their personal information.

patterns:
  first-name:
    title: "First Name"
    description: |
      The first name field allows the customer to enter their first name.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  last-name:
    title: "Last Name"
    description: |
      The last name field allows the customer to enter their last name.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  address:
    title: "Address"
    description: |
      The address field allows the customer to enter their home address.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  postal-code:
    title: "Postal Code"
    description: |
      The postal code field allows the customer to enter their home postal code.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  email:
    title: "Email"
    description: |
      The email field allows the customer to enter their personal email.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  delivery-instructions:
    title: "Delivery Instructions"
    description: |
      The delivery instructions field allows the customer to enter special delivery instructions for their order.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
  check-box:
    title: "Check Box"
    description: |
      The check box field allows the customer to choose whether or not to have their order delivered to their home address.
  country:
    title: "Country"
    description: |
      The country field allows the customer to choose from a list of available countries.
    fields:
      - name: data
        type: object
        data:
          source: "site.checkout[0]"
          type: checkout
