title: "Cards"
description: |
  Cards can be used to display a grouping of elements in a visually pleasing way.

patterns:
  cart-card:
    title: "Cart Card"
    description: |
      The cart card should be used to display the products that have been added to the customers cart.
  image-card:
    title: "Image Card"
    description: |
      The image card should be used as a visually pleasing link to another page.
    fields:
      - name: data
        type: object
        data:
          source: "site.home-cards[0]"
          type: home-card
  product-card:
    title: "Product Card"
    description: |
      The product card should be used to display different products that can be purchased.
    fields:
      - name: data
        type: object
        date:
          source: "site.products[0]"
          type: product
  details-card:
    title: "Details Card"
    description: |
      The details card should be used to display a product and all of the information related to that product.
    fields:
      - name: data
        type: object
        data:
          source: "site.product-details[0]"
          type: product-detail
