title: "Banners"
description: |
  Banners can be used to display photos or bring together other elements.

patterns:
  image-banner:
    title: "Image Banner"
    description: |
      The image banner should be used to display images and create interest on a page.
